src/plone/app/mosaic/profiles/default/registry.xml

See also https://github.com/plone/plone.app.standardtiles/pull/12

Rename "proxy tile" to "existing content tile"

---

CHANGES.rst
src/plone/app/mosaic/configure.zcml

Removed "for" in register default profile for sane installation state.

---

.travis.yml
docs/_selectors.robot

Fix install selector for Plone 4

---

src/plone/app/mosaic/utils.py

Added some basic documentation on how to use the functionality to hide a layout from a specific content type.

Added some basic documentation on how to use the functionality to hide a layout from a specific content type.

---

.travis.yml

If test passes and we want to do so.

Switch CI to use phantomjs

---

src/plone/app/mosaic/profiles/default/metadata.xml
src/plone/app/mosaic/profiles/default/registry.xml
src/plone/app/mosaic/profiles/upgrades/to_5016/registry.xml
src/plone/app/mosaic/transform.py
src/plone/app/mosaic/upgrades.py
src/plone/app/mosaic/upgrades.zcml
src/plone/app/mosaic/utils.py

fix for #195, added missing fields to list of fields to be omitted from editor fields

Omit fields - fixes 195

---

CHANGES.rst
src/plone/app/mosaic/profiles/default/metadata.xml
src/plone/app/mosaic/testing.py

Since we're Plone 5 only we can do this in a clean way.

depend on pact

---

CHANGES.rst
src/plone/app/mosaic/transform.py

for some reason sometimes the view was not found. this should not happen.

Log warning if plone_pattern_settings view was not found.

---

.travis.yml
CHANGES.rst
base.cfg
docs/getting-started.rst

It seems to be a timing issue, as locally it runs fine.

Fix robot framework tests

---

CHANGES.rst
src/plone/app/mosaic/layouts/site/default.html
src/plone/app/mosaic/layouts/site/full-width.html
src/plone/app/mosaic/layouts/site/portlets-left.html
src/plone/app/mosaic/layouts/site/portlets-right.html

Replace ``>`` by ``&gt;``
Fixes:
https://github.com/plone/plone.app.mosaic/issues/199

Make layouts HTML valid

---

CHANGES.rst
setup.py
src/plone/app/mosaic/browser/static/js/mosaic.tile.js
src/plone/app/mosaic/profiles/default/registry.xml
src/plone/app/mosaic/profiles/upgrades/to_5017/registry.xml
src/plone/app/mosaic/upgrades.py
src/plone/app/mosaic/upgrades.zcml

instead of the deprecated plone.app.standardtiles.rawhtml

Move to using plone.app.standardtiles.html for persistent tile

---

CHANGES.rst
Makefile
develop.cfg
sources.cfg
src/plone/app/mosaic/browser/static/js/mosaic.core.js
src/plone/app/mosaic/browser/static/js/mosaic.layout.js
src/plone/app/mosaic/browser/static/js/mosaic.toolbar.js
src/plone/app/mosaic/profiles/default/registry.xml
src/plone/app/mosaic/tests/test_widget.py
src/plone/app/mosaic/widget.py

This requires https://github.com/plone/plone.app.blocks/pull/44 to be completed

Change to use 'customLayout' instead of 'content' for custom content layouts

---

CHANGES.rst
resources/src/plone-mosaic/logged-in.less
src/plone/app/mosaic/browser/static/css/mosaic.authoring.dragging.less
src/plone/app/mosaic/browser/static/css/mosaic.pattern.less
src/plone/app/mosaic/browser/static/js/mosaic.layout.js

Add outline mode when ALT-modifier is pressed

---

CHANGES.rst
src/plone/app/mosaic/browser/static/mosaic-grid.js
src/plone/app/mosaic/profiles/default/registry.xml

Fix issue where mosaica-grid-bundle broke bundle merge

---

CHANGES.rst
src/plone/app/mosaic/browser/static/css/mosaic.pattern.less
src/plone/app/mosaic/browser/static/plone-mosaic.css

fixes https://github.com/plone/plone.app.mosaic/issues/307 and https://github.com/plone/plone.app.mosaic/issues/308

fix the responsive-grid-fix

---

CHANGES.rst
src/plone/app/mosaic/browser/static/css/mosaic.layouts.less
src/plone/app/mosaic/browser/static/js/mosaic.core.js

...this time putting code into the right place, not the bundle.

show layouts description from manifest.cfg

---

CHANGES.rst
src/plone/app/mosaic/widget.py

Fix issue where Mosaic Editor was activated on babel edit view

---

CHANGES.rst
src/plone/app/mosaic/browser/static/js/mosaic.actions.js
src/plone/app/mosaic/browser/static/js/mosaic.core.js
src/plone/app/mosaic/browser/static/js/mosaic.tile.js
src/plone/app/mosaic/browser/static/js/mosaic.toolbar.js

Add queue for tile auto-save requests to git less change for write conflict errors

---

.gitignore
.travis.yml
CHANGES.rst
Makefile
README.rst
base.cfg
bin/compile
bin/detect
bin/release
bootstrap.py
buildout.cfg
develop.cfg
requirements.txt
setup.py
sources.cfg
src/plone/app/mosaic/browser/editor.py
src/plone/app/mosaic/browser/main_template.py
src/plone/app/mosaic/forms.py
src/plone/app/mosaic/registry.py
src/plone/app/mosaic/setuphandlers.py
src/plone/app/mosaic/tests/test_setup.py
src/plone/app/mosaic/transform.py
src/plone/app/mosaic/utils.py
test-5.0.x.cfg
test-5.2.x.cfg
versions.cfg

Reverts plone/plone.app.mosaic#431

Revert "WIP: support Plone 5.2.x for py2.7 and python3"

---

CHANGES.rst
src/plone/app/mosaic/registry.py

cherry-pick missing commit https://github.com/plone/plone.app.mosaic/pull/431/commits/71f2aecb12ce49c4c5ed639eee2ef30d53f72a9d

fix action button sorting

---

CHANGES.rst
src/plone/app/mosaic/registry.py

Safely read tile registry

---

CHANGES.rst
src/plone/app/mosaic/browser/main_template.py
src/plone/app/mosaic/tests/robot/test_editor.robot

in cook_layout method:
string conversion it should different handled because the XMLSerializer returns bytestring in py3

Fix bytestring join in main_template.py

---

CHANGES.rst
Makefile
package.json
src/plone/app/mosaic/browser/static/css/mosaic.authoring.tiles.less
src/plone/app/mosaic/browser/static/css/mosaic.grid.less
src/plone/app/mosaic/browser/static/css/mosaic.pattern.less
src/plone/app/mosaic/browser/static/css/mosaic.toolbar.less
src/plone/app/mosaic/browser/static/mosaic-grid.css
src/plone/app/mosaic/browser/static/plone-mosaic.css
src/plone/app/mosaic/profiles/default/metadata.xml
src/plone/app/mosaic/profiles/default/registry.xml
src/plone/app/mosaic/tests/robot/test_editor.robot
src/plone/app/mosaic/upgrades.zcml

Use only bootstrap grid import to avoid duplicated CSS selectors

---

src/plone/app/mosaic/browser/static/css/layouts-editor.less

Replaces bootstrap with bootstrap3 path. Fonts are only in boostrap3.

Update bs3 paths

---

CHANGES.rst
src/plone/app/mosaic/tests/test_setup.py

modified:   CHANGES.rst
modified:   src/plone/app/mosaic/tests/test_setup.py

Fix Flake8 errors.

---

.pre-commit-config.yaml
resources/js/mosaic.pattern.js
resources/js/templates/delete_layout.xml
resources/js/templates/manage_layouts.xml
resources/js/templates/save_layout.xml
resources/js/templates/select_layout.xml
tox.ini

...and layout selection modal positioning

Fix js templates broken by zpretty

---

CHANGES.rst
MANIFEST.in
README.rst
news/585.feature
package.json
pyproject.toml
resources/js/mosaic.tile.js
tox.ini

TinyMCE 6 fixes

---

.editorconfig
.flake8
.github/dependabot.yml
.github/workflows/meta.yml
.github/workflows/test.yml
.gitignore
.meta.toml
.pre-commit-config.yaml
mx.ini
news/616.bugfix
pyproject.toml
src/plone/app/mosaic/utils.py
tox.ini

Fix calculating widgetName for `IEventBasic` types
